apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    obs.logging.component: log-storage

resources:
- ./loki-operator-application.yaml
- ./loki-operator
# - ./cluster-logging-operator-bundle
# - ./log-file-metric-exporter
# - ./vector

patches:
- patch: |-
    - op: replace
      path: /spec/source/git/url
      value: https://github.com/jcantril/konflux-log-storage
  target:
    kind: Component
