apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../../base
- application.yaml

patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: cluster-logging-catalog
    target: 
      kind: Component
