apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -v6-2
resources:
  - ../log-collection-base
  - ../log-storage-base

patches:
  - target:
      kind: Application
      name: cluster-logging-operator
    path: cluster-logging-operator-application-patch.yaml
  - target:
      kind: Application
      name: loki-operator
    path: loki-operator-application-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/source/git/revision
        value: release-6.2
    target:
      kind: Component
  - patch: |-
      - op: replace
        path: /spec/application
        value: cluster-logging-operator-v6-2
    target:
      kind: Component
      labelSelector: "obs.logging.component=log-collection"
  - patch: |-
      - op: replace
        path: /spec/application
        value: loki-operator-v6-2
    target:
      kind: Component
      labelSelector: "obs.logging.component=log-storage"
  # - target:
  #     kind: Component
  #   path: component-patch.yaml
  # - target:
  #     kind: Component
  #     name: assisted.*
  #   path: ocm-branch-patch.yaml
  # - target:
  #     kind: Component
  #     name: hypershift-release.*
  #   path: openshift-branch-patch.yaml
  # - target:
  #     kind: Component
  #     name: cluster-api.*
  #   path: openshift-branch-patch.yaml
  # - target:
  #     kind: Component
  #     name: hive.*
  #   path: hive-branch-patch.yaml
  # - patch: |-
  #     - op: replace
  #       path: /spec/source/git/revision
  #       value: release-4.17
  #   target:
  #     kind: Component
  #     name: "apiserver-network-proxy.*"
  # - patch: |-
  #     - op: replace
  #       path: /spec/source/git/revision
  #       value: release-ocm-2.12
  #   target:
  #     kind: Component
  #     name: "cluster-api-provider-agent.*"
  # - patch: |-
  #     - op: replace
  #       path: /spec/source/git/revision
  #       value: master
  #   target:
  #     kind: Component
  #     name: "aws-encryption-provider.*"
