apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -v6-2
resources:
  - ../log-collection-base
  - ../log-storage-base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/git/revision
        value: release-6.2
    target:
      kind: Component
  - patch: |-
      - op: replace
        path: /spec/description
        value: "Pipeline for Cluster Logging Operator 6.2"
      - op: replace
        path: /spec/displayName
        value: "Cluster Logging Operator 6.2"
    target:
      kind: Application
      labelSelector: "obs.logging.component=log-collection"
  - patch: |-
      - op: replace
        path: /spec/description
        value: "Pipeline for Cluster Logging Operator 6.2"
      - op: replace
        path: /spec/displayName
        value: "Cluster Logging Operator 6.2"
    target:
      kind: Application
      labelSelector: "obs.logging.component=log-storage"
  - patch: |-
      - op: replace
        path: /spec/application
        value: cluster-logging-operator-v6-2
    target:
      kind: Component
      labelSelector: "obs.logging.component=log-collection"
  - patch: |-
      - op: replace
        path: /spec/application
        value: loki-operator-v6-2
    target:
      kind: Component
      labelSelector: "obs.logging.component=log-storage"